### ISSUE TITLE
Question:  device.set_byte in new luma /  Migrating old code to luma 

### ISSUE THREAD

**Issue by sysmatt** [rm-hull/luma.led_matrix#258]
Hi, I am rewriting some code based on the older max7219 0.2.3 and trying to migrate to luma.  
In my code i called device.set_byte() to directly set col/row outputs.  Is there a proper way to do this in Luma ?

I am not finding a direct replacement, but perhaps there is a data structure i can manipulate then call device.show() ?

Thanks!
-Matt

**Comment by rm-hull** [comment]
Have a look at the example here: https://luma-led-matrix.readthedocs.io/en/latest/python-usage.html#x8-led-matrices

When you call `with canvas() as draw:` it gives you a Pillow image draw object, so you can use any methods that object offer, so instead of draw.rectangle, you could call draw.point e.g. https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.point

within the with block, you can call draw.point several times (or in a loop, or whatever), and as soon as the with block completes it will render the drawing instructions and flush to the display
